env:
  commonjs: true
  es2021: true
  node: true
extends:
  - airbnb-base
  - prettier
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  arrow-body-style: off
  prefer-arrow-callback": off
  func-names: off
  no-plusplus: off
  no-useless-escape: off
  no-underscore-dangle: off
  no-nested-ternary": off
  import/extensions: ['error', 'ignorePackages', { js: 'always' }]
